name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   
    - uses: actions/checkout@v1
    - name: Installing GTK3
    - run: sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list; sudo apt-get update; sudo apt-get install sudo apt-get install libgtk-3-dev
    - name: Getting V
    - run: cd ~; git clone https://github.com/vlang/v.git
    - name: Entering V dir
    - run: cd ./v
    - name: Building V
    - run: make && ./v -cc gcc -o v v.v
    - name: Symlink V
    - run: sudo ./v symlink
    - name: Run test
    - run: v run ./test.v
