name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installing GTK3 package
      run: sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list; sudo apt-get update; sudo apt-get install libgtk-3-dev
    - name: Installing V
      run: cd ~; git clone https://github.com/vlang/v.git; cd v; make CC=clang; sudo ./v symlink
    - name: Setting Up XORG
    - uses: actions/checkout@v1
    - name: Enabling X Display
      run: v run ./test.v
